### ISSUE TITLE
Triggering scenario

### ISSUE THREAD

**Issue by mdmd09** [gimicze/firescript#11]
Is there a way to trigger a certain scenario in another script?

**Comment by gimicze** [comment]
As of now, unfortunately not. I'll probably have had a look at it by the end of the month. Thanks for the suggestion.

**Comment by gimicze** [comment]
See https://docs.fivem.net/natives/?_0x561C060B and https://github.com/gimicze/firescript/wiki/Commands-&-Usage#pre-defining-a-fire-creating-a-scenario-and-then-starting-it
