### ISSUE TITLE
whitelisted dispatch

### ISSUE THREAD

**Issue by jaylac2000** [gimicze/firescript#15]
**Is your feature request related to a problem? Please describe.**

add it so we can add permanent dispatch system to certain players and maybe keep a temp one the side

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gimicze** [comment]
Unclearly and foolishly filled feature request. Feel free to open a new one whenever you feel ready to *also* put some work into it on your side.

**Comment by jaylac2000** [comment]
how is it foolish? im asking for a way where i dont need to /firedispatch add USER everytime they join

**Comment by gimicze** [comment]
You haven't provided proper description and there's a reason the issue templates are set up the way they are.

Anyway, the request is frivolous and more details are needed for anyone to understand what exactly you're looking for. The script already features a built in connection with ESX which you can set up easily through the config. Should you need anything else, feel free to (a) write a detailed feature request and wait till I have the time; or (b) create a fork of your own implementing the desired logic.
