### ISSUE TITLE
QBCore

### ISSUE THREAD

**Issue by BlackDahlia313** [gimicze/firescript#17]
I see you have the ability to tie it to a ESX job. Could you please add qbcore support?

**Comment by Zy0exe** [comment]
@scarecrow313 
What do you exactly mean tie to a job, QBCore doesn't really have a "FireFighter" Job or anything related.
If you mean just that, there is plenty of examples tru scripts like the police or hospital script.

But if you need help regarding that just reply here

**Comment by scarecrow313** [comment]
In config there is a spot for automatic whitelisting for a custom job name in ESX. 

I'm just asking to do the same thing for qb. 

`enableESX = "fd" -- Set to a ESX job / jobs you want to be automatically subscribed to dispatch; Set to nil or false if you don't want to use this`

Hopefully that clears it up :)

**Comment by Zy0exe** [comment]
It is actually just as easy as you think you should be looking forward into rewriting 
```lua

-- Job --
RegisterNetEvent("esx:setJob")

--Setjob would be:
RegisterNetEvent("QBCore:Client:OnJobUpdate")

--------
RegisterNetEvent("esx:playerLoaded")

--PlayerLoaded would be:
RegisterNetEvent("QBCore:Client:OnPlayerLoaded")
```

And ofc you need to change the core obj (You can always import the file in the core if you have it and remove this bit of code)
```lua
QBCore = nil

TriggerEvent('QBCore:GetObject', function(obj) QBCore = obj end)
```
What i meant by "there is plenty of examples throughout the scripts" is there are plenty of pieces of code related to what i just pointed out you need to modify in order to achieve what you want, I won't spoonfeed you with code unless you really can't do it.

**Comment by P4R4NORM4L** [comment]
I would have to bump this... If you could write a QBcore version of it, that would be awesome!

**Comment by Zy0exe** [comment]
> I would have to bump this... If you could write a QBcore version of it, that would be awesome!

Check the PR'S

**Comment by P4R4NORM4L** [comment]
Ok Cool I copied the 4 files into my firescript everything work except for the dispatch aspect of it, I don't get any notifications at all when a scenario is started. Could you please look into that ?

**Comment by LightUpFam** [comment]
bump.  qbcore looking to implement dispatch.

**Comment by Zy0exe** [comment]
> bump. qbcore looking to implement dispatch.

Can you elaborate?

**Comment by LightUpFam** [comment]
> > bump. qbcore looking to implement dispatch.
> 
> Can you elaborate?

Yes, looking to use this on my QBcore server.
I could not get any kind of notifications.

Please make away to notify "firefighter" or whatever job role someone configs

**Comment by Zy0exe** [comment]
> > > bump. qbcore looking to implement dispatch.
> > 
> > 
> > Can you elaborate?
> 
> Yes, looking to use this on my QBcore server. I could not get any kind of notifications.
> 
> Please make away to notify "firefighter" or whatever job role someone configs

The chat gets a red notification, saying the fire has started.

**Comment by LightUpFam** [comment]
how would firefighter know where fires are????? need to notify the job and put blip on map for the fire

**Comment by Zy0exe** [comment]
> how would firefighter know where fires are????? need to notify the job and put blip on map for the fire

it does that it's a red blip of a flame

**Comment by gimicze** [comment]
> I see you have the ability to tie it to a ESX job. Could you please add qbcore support?

See #37
