### ISSUE TITLE
No random fire start

### ISSUE THREAD

**Issue by kevintransp** [gimicze/firescript#2]
Like this mod, seems to first one to be working. But iam having problem with random spawns of fires.
For what i understand from the config file is that i create a fire with "/addflame <spread> <chance>" then its saved in  the file fires.json like this
`[{"flames":[],"dispatchCoords":{"x":342.9586486816406,"y":-542.047607421875,"z":28.74435997009277}}]`

settings in config are
`Config.Fire = {
    fireSpreadChance = 15, -- Out of 100 chances, how many lead to fire spreading? (not exactly percents)
    maximumSpreads = 5,
    spawner = { -- Requires the use of the built-in dispatch system
        enableOnStartup = true,
        frequency = 300, -- Random fire spawn interval (set to nil or false if you don't want to spawn random fires) in ms 900000
        chance = 75, -- Fire spawn chance (out of 100 chances, how many lead to spawning a fire?); Set to values between 1-100
        players = 1, -- Sets the minimum number of players subscribed to dispatch for the spawner to spawn fires.
        firefighterJobs = { -- If using ESX (Config.Dispatch.enableESX), you can specify which players will count as firefighters in Config.Fire.spawner.players above; If not using ESX you can set this to nil
            ["fire"] = true -- Always set the job name in the key, value has to be true
        }
    }
}`

Did i somehting wrong? I'm having the job "fire".

**Comment by gimicze** [comment]
Hi.

I'll try to explain how the system works in simple steps.

- register a fire using `/registerfire` (this command will send the `registeredFireID` I'm referring to later on *in the chat*)
- add flames using `/addflame <registeredFireID> <spread> <chance>` 
**a)** `registeredFireID` is the ID which you will have got after completing the first step
**b)** `spread` is how much you want the specific fire source to spread (I'd recommend staying below 20)
**c)** `chance` is an integer from 0 to 100, specifying how quick the fire spreads
**Note:** You can add as many flames (fire sources) to a registered fire as you want **BUT** some computers may not be able to cope with large amount of particles - the lower you keep it, the better the performance.
- register the fire to the spawner using `/randomfires add <registeredFireID>`

Note that you might have to reconnect or add yourself manually to the dispatch feed for the spawner to work.

As this is rather a question than an issue with the script let me know if this help so I can close it. I will, however, have a look at the documentation which appears to be insufficient or too complicated as I have been receiving similar questions the past few weeks.

**Comment by kevintransp** [comment]
Thanks for your reply, gone try to add random fires with this explaining. Makes more sense now.

**Comment by gimicze** [comment]
Has this helped you to resolve your problem or do you need any further help?

**Comment by gimicze** [comment]
If you still encounter any problems, feel free to open another issue.
