### ISSUE TITLE
Dispatch

### ISSUE THREAD

**Issue by frazz1234** [gimicze/firescript#21]
The possibility to delete easy the blip when the fire is down or is deleted when your show up on the scene ! 

The possibility in the config to make dispatch by default for all firefighter, so no need to be a dispatch... just they receive the call whit the sound and let's go ! 

could be amazing

**Comment by gimicze** [comment]
> The possibility to delete easy the blip when the fire is down or is deleted when your show up on the scene !

You can replace this

https://github.com/gimicze/firescript/blob/86c7ed7297d5fe7e26d21ddafeb7346e3302c271/client/dispatch.lua#L162

with something like `Dispatch:clear(Dispatch.lastCall)`.

> The possibility in the config to make dispatch by default for all firefighter, so no need to be a dispatch... just they receive the call whit the sound and let's go !

This is already implemented for ESX. For other frameworks, I would point you to the code following this line:

https://github.com/gimicze/firescript/blob/86c7ed7297d5fe7e26d21ddafeb7346e3302c271/server/main.lua#L579
