### ISSUE TITLE
London Studios Fire Tools (Water Monitor + Hose) Compatibility

### ISSUE THREAD

**Issue by SushiCoochie** [gimicze/firescript#24]
**Is your feature request related to a problem? Please describe.**
This is a feature request related to a problem since i cannot use some of my tools in my london studios files with this script like the water monitor and hose.

**Describe the solution you'd like**
Compatibility between this script and london studios scripts

**Describe alternatives you've considered**
Ive tried using the other fire script but that didnt compare, tried adding it into the script didnt work.

**Comment by gimicze** [comment]
Hi! This script uses natives to spawn fire and particle FX in a certain manner - it shouldn't interfere with any other scripts. And at the same time any water source should put the fire out eventually. Do you still encounter any problems?
