### ISSUE TITLE
Dispatch removes after you give someone the permissions

### ISSUE THREAD

**Issue by Onfyregaming** [gimicze/firescript#26]
Dispatch wont save permissions

just wondering what  dispatch permissions do we need to make it so it remembers who is whitelisted etc and is there meant to be a line in the server config file we needed to add???

been trying everything and just cant work it out...

sorry for buggin you but we really like the script and thats the only issue we are having...

**Comment by gimicze** [comment]
Hi.

Which commands are you using to add players to the whitelist? Try removing whitelist.json from the script's directory. Can you check whether any changes are made to the file after i.e. `/firewl add <nick>`?

If you want to whitelist a certain ace group permanently, you can easily add ace permission `firescript.all`.

**Comment by Onfyregaming** [comment]
thats all fine but the issue is setting people to get dispatch notification when a fire starts, how can we make it so they automatically get the dispatch alerts when a fire starts?? cause everytime someone logs out they need to be given the dispatch command again..

**Comment by gimicze** [comment]
Oh, right.

Are you using ESX?

**Comment by Onfyregaming** [comment]
qb-core

**Comment by gimicze** [comment]
Then you could try using this community-modified version from a pull-request:

https://github.com/gimicze/firescript/pull/19

You only need to set tho job name in config.lua. Not sure whether it works well, though, as some report it having some problems.

I unfortunately don't have a QB server set-up and neither the time to test it and possibly make it work fully.
