### ISSUE TITLE
Stop the smoke damage on somes locations

### ISSUE THREAD

**Issue by davoucci** [gimicze/firescript#28]
**Describe the bug**
When we are in the pizzeria or in the mine, we got damage from smoke. 
**To Reproduce**
1. Go to 'Gabz Pizzeria or Mine'
2. See error

**Expected behavior**
A exception list or something like that.

**Comment by gimicze** [comment]
Unfortunately couldn’t reproduce. I suspect it’s more the interior's problem than the script's though.
