### ISSUE TITLE
Issue updates not in OG package?

### ISSUE THREAD

**Issue by ShaAlexander** [gimicze/firescript#32]
Hi there, 

Sorry to bother you with this, but I found out that over the years you've given a lot of patched code in replies to issue posts. 
However, the latest updated file within the code, is like 2 years ago? Is it me or are those codes 'new' not in the original files? 

thanks!

**Comment by gimicze** [comment]
Hi!

What code are you referring to? I'm not even sure whether I've ever patched code as a reaction to one of the issues posted here 😄 The latest code in the repository should be up-to-date.

Let me know if I'm missing anything.
