### ISSUE TITLE
[Bug] Fire sometimes dont properly spawn/show up and sound gets stuck

### ISSUE THREAD

**Issue by Ma-Ko-dev** [gimicze/firescript#40]
**Describe the bug**
Sometimes, i havent properly reproduced it yet, the fire from a random fire starts, but the flames wont show properly. There are only these tiny "ground" flames to see. You can still extinguish the fire, but the sound wont stop. There are also no errors.

**To Reproduce**
As i mentioned, i wasnt able to reproduce it. Sometimes it happens after i restart the script, sometimes after i  extinguished the first fire. I Keep trying to reproduce it consistently.

**Expected behavior**
I expect to see big flames and the sound to dissapear when the fire is out. :D

**Screenshots**
Will add a screenshot of the tiny flames if necessary.

**Server (please complete the following information):**
 - Artifact: [7290]
 - Script version: [2.0.0]

**Comment by gimicze** [comment]
Thanks for the report. Let me know if you find out anything else. I have done some extensive testing recently and haven't experienced anything similar - maybe restarting the script multiple times while the server is running doesn't do much good. I haven't found any code which would point to this happening yet. Regardless, if anybody else reads this and has experienced it, reach out 😇

**Comment by DetErDugget** [comment]
I'm sure that the issue is due to the Ptfx being unloaded automatically.
It should be loaded right before the use of smoke and fire fx.

**Comment by gimicze** [comment]
That should be it. Thanks 🙂 Commit d687fb02987f66612ccacb1d806c1d5f68d100fc should fix this. @Ma-Ko-dev, please, download the latest code from main branch and see if the issue persists.
